### PR TITLE
notice search and filter functionality updated

### PR DESCRIPTION
**Pull request by khemrajshrestha471**
notice's search and filter functionality updated

### CODE REVIEW

**Comment by ompiepy** [comment]
image
suru ko page ma page 1 dekhaudaina khem milauna milcha

**Comment by ompiepy** [comment]
UI ko type ma add gara hai sabai option aru ta thik xa

**Comment by khemrajshrestha471** [comment]
first page ma 1 chaidaina

aaru page ma gayo vane 1 aafai aayuxa om
________________________________

**Comment by khemrajshrestha471** [comment]
> UI ko type ma add gara hai sabai option aru ta thik xa

bujena yo

**Comment by ompiepy** [comment]
image
ahile yesma tin ota matrai xa ni yesma sabai options haru rakhideu bhaneko select garna milne

**Comment by khemrajshrestha471** [comment]
okay

**Pull request merged**
